stages:
- understand-analysis
- understand-kaloi
- s101-metric

# now the jobs

build:understand-analysis:
   stage: understand-analysis
   tags: # runner tag - you passed it when you registered the runner
   - understand
   artifacts:
    paths:
    - ping.udb
   script:
   - echo "Running Understand" # make sure the runner machine has this in the PATH: /Applications/scitools/bin/macosx
   - und create -languages python ping.udb # if python3, pass also: -PythonSetVersion python3
   - und add . ping.udb
   - und analyze ping.udb

build:understand-kaloi:
   stage: understand-kaloi
   dependencies:
   - build:understand-analysis
   tags: # runner tag - you passed it when you registered the runner
   - understand
   script:
   - echo "Cap on max metrics" # make sure the runner machine has this in the PYTHONPATH: /Applications/scitools/bin/macosx/python
   - srccheck --in=ping.udb --maxFileMetrics='{"CountLineCode":500,"CountDeclFunction":30,"CountDeclClass":1}' --maxClassMetrics='{"CountDeclMethod":20,"MaxInheritanceTree":4}' --maxRoutineMetrics='{"CountLineCode":80,"CountParams":7,"CyclomaticModified":7}' --maxPrjMetrics='{"AvgCyclomaticModified":3,"MaxNesting":5}' --verbose

build:s101-analysis:
   stage: s101-metric
   dependencies:
   - build:understand-analysis
   tags: # runner tag - you passed it when you registered the runner
   - s101
   script:
   - echo "Running s101"
   - java -Xmx512m -Djava.library.path=/Users/mqm/s101-build -jar /Users/mqm/s101-build/structure101-gen-build.jar ping.build.xml
   # sh s101.sh